#    COPYRIGHT (C) 2025 Mitsubishi Electric Corporation

#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at

#        http://www.apache.org/licenses/LICENSE-2.0

#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Binary IO control mode Fields Required
bool general1_io_interface
bool general2_io_interface
bool user1_io_interface
bool user2_io_interface
bool user3_io_interface
bool user4_io_interface
bool user5_io_interface
bool user6_io_interface
bool user7_io_interface
bool user8_io_interface
